safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Sangsoo Yoon"
description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"
baseurl: "/onepage"
url: "https://ysan9500.github.io" # replace by your site's url
twitter_username: ysan9500
github_username:  ysan9500 # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Sangsoo Yoon"
address: "Seobu-ro, <br>Suwon, South Korea"
email: "email@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
